[build]
  base = "backend"
  publish = "backend"
  functions = "backend/netlify/functions"

[context.production.environment]
  NODE_ENV = "testnet"
  NETWORK = "sepolia"
  CHAIN_ID = "11155111"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 