[build]
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[context.production.environment]
  NODE_ENV = "testnet"
  NETWORK = "sepolia"
  CHAIN_ID = "11155111" 